language: php

notifications:
  email: false

env:
  global:
  - USER="username"
  - EMAIL="username@mail.com"
  - REPO="hammer_theatre"
  - GH_REPO="github.com/HA-SJSU/${REPO}.git"

script:
  - ls -a
  - git remote add staging git@git.wpengine.com:staging/hammertheatre.git
  - 


