version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: ls -al

  deploy:
    machine:
        enabled: true
    steps:
      - checkout
      - run:
          name: Show all dir and files
          command: ls -al

      - run:
          name: ssh info to staging server
          command: ssh -v git@git.wpengine.com info 

      - run:
          name: Git config
          command: |
            git status
            git remote add staging git@git.wpengine.com:staging/hammertheatre.git

      - run:
          name: Deploy to staging
          command: |
            git push staging master

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
