version: 2
jobs:
  deploy:
        # working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run:
          name: Show all files
          command: ls -al

      - run:
          command: |
            git status

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy
