version: 2
jobs:
  build:
    machine:
      php:
        version: 7.0.4
    
    steps:
      - checkout
      - run: ls -al

  deploy:
    machine
        # working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run:
          name: Show all files
          command: ls -al

      - run:
          command: |
            git status

workflows:
  version: 2
  deploy:
    jobs:
      - build
      - deploy
